### ISSUE TITLE
ImportError: No module named 'binance'

### ISSUE THREAD

**Issue by sorentorp** [sQu1rr/binance-dust-sweeper#10]
> xxx@server:~/build/binance-dust-sweeper-master$ ./dustsweeper.py --dry-run
> Traceback (most recent call last):
>   File "./dustsweeper.py", line 5, in <module>
>     from belks.binance.dustsweeper import DustSweeper
>   File "/home/xxx/build/binance-dust-sweeper-master/belks/binance/dustsweeper.py", line 3, in <module>
>     from binance.client import Client
> ImportError: No module named 'binance'
> 

I have installed binance, python-binance & simple-crypt
Python --version
Python 2.7.9
and 
Python 3.4.2

**Comment by sQu1rr** [comment]
it sounds like python-binance is not installed (i know you are saying it is, make sure it is installed for the correct python version)

**Comment by sorentorp** [comment]
Hmm, wierd... This is the most critical part of the install... Any ideas?

`pip3 install python-binance`

```
  Downloading from URL https://pypi.python.org/packages/8f/39/77c555d68d317457a10a30f4a92ae4a315a4ee0e05e9af7c0ac5c301df10/ruamel.yaml-0.15.35.tar.gz#md5=13b93b987fe1881b66c7cbccdf58c731 (from https://pypi.python.org/simple/ruamel.yaml/)
  Running setup.py (path:/tmp/pip-build-_d9wdq_v/ruamel.yaml/setup.py) egg_info for package ruamel.yaml
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2382, in _dep_map
        return self.__dep_map
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2457, in __getattr__
        raise AttributeError(attr)
    AttributeError: _Distribution__dep_map

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-_d9wdq_v/ruamel.yaml/setup.py", line 917, in <module>
        main()
      File "/tmp/pip-build-_d9wdq_v/ruamel.yaml/setup.py", line 905, in main
        setup(**kw)
      File "/usr/lib/python3.4/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 266, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python3.4/distutils/dist.py", line 280, in __init__
        self.finalize_options()
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 300, in finalize_options
        ep.require(installer=self.fetch_build_egg)
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2201, in require
        reqs = self.dist.requires(self.extras)
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2401, in requires
        dm = self._dep_map
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2390, in _dep_map
        if invalid_marker(marker):
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1207, in is_invalid_marker
        cls.evaluate_marker(text)
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1319, in _markerlib_evaluate
        for key in env.keys():
    RuntimeError: dictionary changed size during iteration
    sys.argv ['-c', 'egg_info', '--egg-base', 'pip-egg-info']
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2382, in _dep_map

    return self.__dep_map

  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2457, in __getattr__

    raise AttributeError(attr)

AttributeError: _Distribution__dep_map



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-_d9wdq_v/ruamel.yaml/setup.py", line 917, in <module>

    main()

  File "/tmp/pip-build-_d9wdq_v/ruamel.yaml/setup.py", line 905, in main
    setup(**kw)

  File "/usr/lib/python3.4/distutils/core.py", line 108, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 266, in __init__

    _Distribution.__init__(self,attrs)

  File "/usr/lib/python3.4/distutils/dist.py", line 280, in __init__

    self.finalize_options()

  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 300, in finalize_options

    ep.require(installer=self.fetch_build_egg)

  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2201, in require

    reqs = self.dist.requires(self.extras)

  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2401, in requires

    dm = self._dep_map

  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2390, in _dep_map

    if invalid_marker(marker):

  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1207, in is_invalid_marker

    cls.evaluate_marker(text)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1319, in _markerlib_evaluate

    for key in env.keys():

RuntimeError: dictionary changed size during iteration

sys.argv ['-c', 'egg_info', '--egg-base', 'pip-egg-info']

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-_d9wdq_v/ruamel.yaml
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1230, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python3/dist-packages/pip/req.py", line 326, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python3/dist-packages/pip/util.py", line 716, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-_d9wdq_v/ruamel.yaml

```

**Comment by sorentorp** [comment]
I followed your windows guide - worked perfectly...
