### ISSUE TITLE
KeyError: 'BNB'

### ISSUE THREAD

**Issue by dicemans** [sQu1rr/binance-dust-sweeper#7]
root@binance/var/opt/dust# ./dustsweeper.py --dry-run
Connecting to API
Connected
Traceback (most recent call last):
  File "./dustsweeper.py", line 23, in <module>
    helper.set_bnb_prompt(args.bnb_prompt)
  File "/var/opt/dust/belks/binance/dustsweeper.py", line 70, in set_bnb_prompt
    self.bnb_prompt = bool(show) and self.account.has_bnb()
  File "/var/opt/dust/belks/binance/account.py", line 27, in has_bnb
    return self.coins['BNB']['balance'] > 0
KeyError: 'BNB'

**Comment by dicemans** [comment]
i have fixed:

File "belks/binance/account.py", line 27
    return ('BNB' in self.coins) and (self.coins['BNB']['balance'] > 0)

**Comment by sQu1rr** [comment]
duplicate of #1
