### ISSUE TITLE
ImportError: No module named 'dateparser'

### ISSUE THREAD

**Issue by skupfer** [sQu1rr/binance-dust-sweeper#8]
```
python3 --version
Python 3.5.2
```

```
pip3 --version
pip 9.0.1 from /home/user/.local/lib/python3.5/site-packages (python 3.5)
```

```
Successfully built simple-crypt Twisted pycrypto pycparser
Installing collected packages: six, idna, pycparser, cffi, asn1crypto, cryptography, pyOpenSSL, pyasn1, attrs, pyasn1-modules, service-identity, setuptools, zope.interface, constantly, incremental, Automat, hyperlink, Twisted, txaio, autobahn, chardet, certifi, urllib3, requests, python-binance, pycrypto, simple-crypt
Successfully installed Automat Twisted asn1crypto attrs autobahn certifi cffi chardet-2.3.0 constantly cryptography-1.2.3 hyperlink idna-2.0 incremental pyOpenSSL pyasn1-0.1.9 pyasn1-modules pycparser pycrypto python-binance requests-2.9.1 service-identity setuptools-20.7.0 simple-crypt six-1.10.0 txaio urllib3-1.13.1 zope.interface
```

```
./dustsweeper.py --dry-run
Traceback (most recent call last):
  File "./dustsweeper.py", line 5, in <module>
    from belks.binance.dustsweeper import DustSweeper
  File "/mnt/c/git/github/binance-dust-sweeper/belks/binance/dustsweeper.py", line 3, in <module>
    from binance.client import Client
  File "/home/user/.local/lib/python3.5/site-packages/binance/client.py", line 9, in <module>
    from .helpers import date_to_milliseconds, interval_to_milliseconds
  File "/home/user/.local/lib/python3.5/site-packages/binance/helpers.py", line 1, in <module>
    import dateparser
ImportError: No module named 'dateparser'
```

**Comment by skupfer** [comment]
NVM `pip3 install dateparser`
